osx_image: xcode9
language: objective-c

before_install:
- git submodule update --init --recursive
- brew update || brew update
- brew outdated xctool || brew upgrade xctool
script:
- xcodebuild -project TestingTravis.xcodeproj -scheme TestingTravis -sdk iphonesimulator
ONLY_ACTIVE_ARCH=NO
